### ISSUE TITLE
salmonella URLs only work at /admin/salmonella

### ISSUE THREAD

**Issue by smcoll** [lincolnloop/django-salmonella#32]
Using `url(r'^foo/salmonella/', include('salmonella.urls')),` in `urls.py` results in 404s for the salmonella requests, for example.  This seems to indicate that the `admin/salmonella` location is hard-coded somewhere.

**Comment by bartTC** [comment]
I added docs how you can modify this path here, https://github.com/lincolnloop/django-salmonella/commit/2230a2daf4b6add411ebbe0acc06956ef0da0d81 

Let me know if anything is unclear.

Note that you don't **have to** use a different path for the Salmonella scripts. The `/admin/` path is hardcoded in the JS file because we have no way to access the context there. 

But you can keep the Salmonella views on `/admin/` while the admin is still located under `foo`. Example:

```
urlpatterns = [
    url(r'^foobar/', admin.site.urls),
    url(r'^admin/salmonella/', include('salmonella.urls')),
]
```
